---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Alter daemon.json to mount data-root on /data
  copy:
    src: templates/etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0

- block:
  - name: Make sure that docker.service.d directory exists
    file:
      path: '/etc/systemd/system/docker.service.d'
      state: 'directory'
      owner: 'root'
      group: 'root'
      mode: '0755'

  - name: Configure Docker http proxy
    template:
      src: 'etc/systemd/system/docker.service.d/http-proxy.conf.j2'
      dest: '/etc/systemd/system/docker.service.d/http-proxy.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'
    notify: ['restart docker' ]

  - name: Configure Docker httpS proxy
    template:
      src: 'etc/systemd/system/docker.service.d/https-proxy.conf.j2'
      dest: '/etc/systemd/system/docker.service.d/https-proxy.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'
    notify: ['restart docker' ]


  - name: Reload systemd daemons
    command: systemctl daemon-reload
    notify: [ 'restart docker']
  when:
    docker_setup_proxy

